name: ecommerce_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auto_route: ^9.2.1+1
  auto_route_generator: ^9.0.0
  bloc: ^8.1.4
  build_runner: ^2.4.12
  country_picker: ^2.0.26
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen_runner: ^5.7.0
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Bold.ttf
  assets:
    - assets/fonts/
    - assets/gifs/


